// <auto-generated />
using System;
using HuGuWeb.TechnicalService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HuGuWeb.TechnicalService.Infrastructure.Migrations
{
    [DbContext(typeof(TechnicalServiceDbContext))]
    partial class TechnicalServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HuGuWeb.TechnicalService.Domain.MaintenanceIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BlocksRoomUse")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OriginNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OutageClassification")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreparationImpact")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportedByEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UnableToResolveNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PropertyId", "Status")
                        .HasDatabaseName("IX_MaintenanceIssues_PropertyId_Status");

                    b.HasIndex("RoomId", "Status")
                        .HasDatabaseName("IX_MaintenanceIssues_RoomId_Status");

                    b.ToTable("MaintenanceIssues", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceIssues_InProgressHasAssignee", "\"Status\" <> 'InProgress' OR \"AssignedEmployeeId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_MaintenanceIssues_Outage", "(\"BlocksRoomUse\" = FALSE AND \"OutageClassification\" IS NULL) OR (\"BlocksRoomUse\" = TRUE AND \"OutageClassification\" IN ('OutOfOrder', 'OutOfService'))");

                            t.HasCheckConstraint("CK_MaintenanceIssues_Priority", "\"Priority\" IN ('Normal', 'High', 'Urgent')");

                            t.HasCheckConstraint("CK_MaintenanceIssues_ResolvedHasNote", "\"Status\" <> 'Resolved' OR (\"ResolutionNote\" IS NOT NULL AND btrim(\"ResolutionNote\") <> '')");

                            t.HasCheckConstraint("CK_MaintenanceIssues_Status", "\"Status\" IN ('Open', 'InProgress', 'UnableToResolve', 'Resolved')");

                            t.HasCheckConstraint("CK_MaintenanceIssues_UnableHasNote", "\"Status\" <> 'UnableToResolve' OR (\"UnableToResolveNote\" IS NOT NULL AND btrim(\"UnableToResolveNote\") <> '')");
                        });
                });

            modelBuilder.Entity("HuGuWeb.TechnicalService.Domain.MaintenanceIssueCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("PropertyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MaintenanceIssueCategories_PropertyId_Name");

                    b.ToTable("MaintenanceIssueCategories", (string)null);
                });

            modelBuilder.Entity("HuGuWeb.TechnicalService.Domain.MaintenanceIssueHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActingUserId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("BlocksRoomUse")
                        .HasColumnType("boolean");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("FromEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromPriority")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutageClassification")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreparationImpact")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ToEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToPriority")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId", "OccurredAt");

                    b.ToTable("MaintenanceIssueHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceIssueHistory_Event", "\"EventType\" IN ('Created', 'Assigned', 'Reassigned', 'PriorityChanged', 'BlockingChanged', 'Started', 'UnableToResolve', 'Resumed', 'Resolved')");
                        });
                });

            modelBuilder.Entity("HuGuWeb.TechnicalService.Domain.MaintenanceIssue", b =>
                {
                    b.HasOne("HuGuWeb.TechnicalService.Domain.MaintenanceIssueCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HuGuWeb.TechnicalService.Domain.MaintenanceIssueHistoryEntry", b =>
                {
                    b.HasOne("HuGuWeb.TechnicalService.Domain.MaintenanceIssue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
